Gradient Descent
-------------------------------

Today I am going to implement the function for gradient descent function as defined by Andrew Ng
in his Machine Learning Coursera course.  

In [4]:
import numpy as np

The first thing that I am going to do is to define the gradient descent function for 
the number of features ($n$), with a training set of size ($m$)

Cost Function:
    $$
     J(\theta_0, \theta_1, ..., \theta_n) = \frac{1}{2m}\sum_{i=1}^{m}(h_\theta(x^{(i)}) - y^{(i)})^2
    $$
    
Gradient Descent (_Repeat until Convergence_):
 
  $$
  \theta_0 := \theta_0 - \alpha\frac{1}{m}\sum_{i=1}^{m}(h_\theta(x^{(i)}) - y^{(i)})* x_0^{(i)}    
  $$
  $$
  \theta_1 := \theta_1 - \alpha\frac{1}{m}\sum_{i=1}^{m}(h_\theta(x^{(i)}) - y^{(i)})* x_1^{(i)}
  $$
  $$
  ...
  $$
  $$
  \theta_n := \theta_n - \alpha\frac{1}{m}\sum_{i=1}^{m}(h_\theta(x^{(i)}) - y^{(i)})* x_n^{(i)}
  $$
  
> Note: There are two things to call out, the first being that $x_0$ is always going to be $1$ as we
are using this weight as our __bias__.  Also the function we are using above is a partial derivative
  $$
  \frac{\partial}{\partial\theta_0} = \frac{1}{m}\sum_{i=1}^{m}(h_\theta(x^{(i)}) - y^{(i)})
  $$

So now that we have this math in mind, lets go ahead an code this up

In [3]:
def gradient_descent(weights, X, y, learning_rate=0.001, convergence=0.001, loops=None):
    assert len(X) == len(y)
    assert len(weights) == len(X[0])+1  # The extra one is because we are treating x_0 as a 1 and the weight as the bias
    
    loops = loops or 10
    
    X_with_0 = [[1] + X_i for X_i in X]
    
    def h_func(X_i, weights):
        return sum([x * w for x,w in zip(X_i, weights)])
        
    for i in range(loops):        
        sample_size = len(X)
        updated_weights = list(weights)
        for j in range(len(weights)):
            updated_weights[j] = weights[j] - learning_rate * (1 / sample_size) * \
               sum([((h_func(X_i, weights) - y_i) * X_i[j]) for X_i, y_i in zip(X_with_0, y)])
            
        weights = updated_weights
        
    return weights

Alright, lets test our function out.  We have the following function that we are trying to predict.  

$$
y = 10 + 3x
$$

We are going to make this an easy example by having the following training examples (no noise).  

$$
m = 4
$$
$$
X = [[7], [2], [10], [5]]
$$
$$
y = [31, 16, 40, 25]
$$

In [19]:
X = [[7], [2], [10], [5]]
y = [31, 16, 40, 25]

weights = np.random.rand(2)
weights

array([0.93697586, 0.85850861])

Ok we have our data and our weights (randomly selected).  Lets see if we can converge on the solution after 100 loops.  

In [24]:
gradient_descent(weights, X, y, loops=100)

[1.5406642823006271, 4.112785570434361]

Obviously we are not there... we can try to see if adjusting the learning rate helps or hinders. 

In [27]:
gradient_descent(weights, X, y, loops=100, learning_rate=0.01)

[2.8596959094733556, 3.966813161875216]

Well that is only a little better... so lets try it with a few more loops.  

In [30]:
gradient_descent(weights, X, y, loops=1000, learning_rate=0.01)

[8.682296034016924, 3.1784200674951433]

So bumping us up from 100 to 1000 had a huge impact... we are almost there... lets bump it up to 10000 now.  

In [32]:
gradient_descent(weights, X, y, loops=10000, learning_rate=0.01)

[9.999999939628895, 3.000000008174383]

Ok, that is pretty good.  For all intents and purposes we were able to correct pick the weights that
completed our function.  

However this was a very simple function... for our next use case lets create a function that has more variables.  

$$
y = 1.2 + 2.5(a) + 1.3(b) - 0.5(c)
$$

And, lets create a training set for this data.  

$$
m = 6
$$
$$
X = [[2, 4, 3], [1, 2, 1], [1, 4, 4], [2, 3, 1], [9, 3, 10], [8, 11, 6]]
$$
$$
y = [9.9, 5.800000000000001, 6.9, 9.600000000000001, 22.6, 32.5]
$$

__Note__: The easiest ways to get Y in this case is just to run the below code.  
        
        y = [(1.2 + (2.5 *i[0]) + (1.3 * i[1]) - (0.5 * i[2])) for i in X]


In [34]:
X = [[2, 4, 3], [1, 2, 1], [1, 4, 4], [2, 3, 1], [9, 3, 10], [8, 11, 6]]
y = [9.9, 5.800000000000001, 6.9, 9.600000000000001, 22.6, 32.5]

weights = np.random.rand(4)
weights

array([0.22927249, 0.26481764, 0.70905633, 0.12221558])

Alright, lets try this with a `learning_rate` of `0.01` and with 1000 loops to start. 

In [35]:
gradient_descent(weights, X, y, loops=1000, learning_rate=0.01)

[0.9990714368777828, 2.46424228663451, 1.3273869935038272, -0.4574399278531272]

Not to bad for the first 1000, lets bump this up to 10000 to see if it gets it. 

In [36]:
gradient_descent(weights, X, y, loops=10000, learning_rate=0.01)

[1.1999999896304487, 2.499999998154821, 1.300000001413358, -0.4999999978037285]

Alright, another success!  So the final example is going to a be a simpiler function, however we
are going to set the bias as a random value.  So for this one, every values of $y$ for a given $X$
will be created using the below function.  

$$
y = random + 1.5(a) + 0.24(b)
$$

We will use the following training set.  

$$
m = 6
$$
$$
X = [[1, 2], [4, 5], [3, 8], [9, 12], [20, 5], [-2, 1]]
$$

In [66]:
X = [[1, 2], [4, 5], [3, 8], [9, 12], [20, 5], [-2, 1]]
y = [np.random.rand() + (1.5 * i[0]) + (0.24 + i[1]) for i in X]
display(y)

weights = np.random.rand(3)
weights

[4.6541430502578685,
 11.475176769715041,
 13.645518577912771,
 26.3388038205697,
 35.40210005589027,
 -1.4848737940545111]

array([0.00182814, 0.21736791, 0.91668627])

Alright... this time we are just going to do a full gradient descent over 10000 loops since that
seems to be the best outcome so far.

In [67]:
gradient_descent(weights, X, y, loops=10000, learning_rate=0.01)

[0.6973566170296959, 1.4753706689947659, 1.0366289504029107]

Hmm... so this is interesting... the $a$ weight seems about right, but the $b$ weight should be $0.24$ and it is $1.03..$ 

Lets see if changing the loops would adjust the count or not.  

In [68]:
gradient_descent(weights, X, y, loops=100000, learning_rate=0.01)

[0.6973566170297408, 1.4753706689947652, 1.0366289504029056]

So introducing the notion of random is causing issues in the outcome... now it is important to note that our training set
was not that large, lets see if it changes if our training set is a bit bigger.  

In [71]:
X = [list(np.random.rand(2)) for _ in range(100)]
y = [np.random.rand() + (1.5 * i[0]) + (0.24 + i[1]) for i in X]

X_test = [list(np.random.rand(2)) for _ in range(10)]
y_test = [np.random.rand() + (1.5 * i[0]) + (0.24 + i[1]) for i in X_test]

weights = np.random.rand(3)
weights

array([0.70038892, 0.04038746, 0.42876696])

In [72]:
trained_weights = gradient_descent(weights, X, y, loops=10000, learning_rate=0.01)
trained_weights

[0.7988220442282105, 1.3890722281566, 0.9841294134371793]

Lets check out or error

In [73]:
y_predict = [(trained_weights[0] + sum([t * i for t, i in zip(trained_weights[1:], x)])) for x in X_test]
error = [np.abs(y_t - y_p) for y_t, y_p in zip(y_test, y_predict)]
display(error)
sum(error)/len(error)

[0.05636550442509569,
 0.014352208553011225,
 0.17928726424453334,
 0.2544133629260583,
 0.10199611080334448,
 0.4954440103818616,
 0.24044108226391137,
 0.42843969631334833,
 0.27286159284824674,
 0.2599763325562625]

0.2303577165315674

Ok for this next example I just want to try the solution on a polynomial function. 

$$
y = 3 + 2.5a + 4b + 1.8a^2 + 0b^2 + 1.1(a*b)
$$

We will also have a sample set of `10` items that are randomly generated, with the corresponding targets. 

In [7]:
X_all = [list(np.random.rand(2)) for _ in range(110)]
y_all = [(3 + (2.5 * i[0]) + (4 * i[1]) + (1.8 * np.exp(i[0])) + (1.1 * i[0] * i[1])) for i in X_all]

X = [[i[0], i[1], np.exp(i[0]), np.exp(i[1]), i[0] * i[1]] for i in X_all[:-10]]
y = y_all[:-10]

X_test = [[i[0], i[1], np.exp(i[0]), np.exp(i[1]), i[0] * i[1]] for i in X_all[-10:]]
y_test = y_all[-10:]

weights = np.random.rand(6)
weights

array([0.79076562, 0.14551373, 0.54934079, 0.01278833, 0.04125727,
       0.77419747])

In [20]:
trained_weights = gradient_descent(weights, X, y, loops=30000, learning_rate=0.2)
trained_weights

[2.9747519479012845,
 2.48389197741206,
 3.967085419441315,
 1.809588801517826,
 0.019184573568546547,
 1.0999038302884239]

In [25]:
y_predict = [(trained_weights[0] + sum([t * i for t, i in zip(trained_weights[1:], x)])) for x in X_test]
error = [np.abs(y_t - y_p) for y_t, y_p in zip(y_test, y_predict)]
display(error)
sum(error)/len(error)

[0.002259869130130099,
 0.0010997269584400726,
 0.000293110361134552,
 0.001597832841696345,
 0.001914420037712361,
 0.0016914197111939089,
 0.0026342602528544035,
 0.002129017828453428,
 0.0011504967980453529,
 0.0007488690675998555]

0.0015519022987260378

So the solution seems to work with polynomials as well, however I did have to do some hyperparameter tuning to come
up with a relatively good solution.  These are some combinations that I used. 

- `learning_rate`: 0.01, `loops`: 10000
- `learning_rate`: 0.1, `loops`: 10000
- `learning_rate`: 0.1, `loops`: 100000
- `learning_rate`: 0.2, `loops`: 10000
- `learning_rate`: 0.2, `loops`: 20000

## Solving using Normal Equation

One thing that we didn't call out, is that we are basically trying to find the location where the derivative for $\theta$
is equal to 0.  For a single feature this is a pretty simple, however for multiple features what we are trying to do is find
the partial derivate for each $\theta_j$ in our $m$ features.  

Luckily this already has a solution for us, using matrices. The function is defined below.  

$$
\theta = (X^TX)^{-1}X^Ty
$$

Now it is important to understand the structure of both $X$ and $y$.  Namely we will need to make sure add hardcoded `1` for
use in calculating the `bias` value.  

$$
 X = \begin{bmatrix}
    1 & 3 & 2 & 5 \\
    1 & 4 & 5 & 1 \\
    ... \\
    1 & 2 & 8 & 3 \\   
  \end{bmatrix}
  Y = \begin{bmatrix}
    5 \\
    22 \\
    ... \\
    13
  \end{bmatrix}
$$

So lets go ahead and create a method for the normal equation.  

In [54]:
def normal_equation(X, y):
    X = np.array(X)
    bias_column = np.ones((len(X), 1))
    X = np.append(bias_column, X, axis=1)
    
    y = np.array(y)
    y = y.reshape((len(X), 1))
    
    return np.linalg.inv(X.T @ X) @ X.T @ y
    #return np.invert(X.T @ X) @ X.T @ y

In [55]:
trained_weights = normal_equation(X, y)
trained_weights

array([[ 3.00000000e+00],
       [ 2.50000000e+00],
       [ 4.00000000e+00],
       [ 1.80000000e+00],
       [-1.09956488e-12],
       [ 1.10000000e+00]])

In [56]:
y_predict = [(trained_weights[0] + sum([t * i for t, i in zip(trained_weights[1:], x)])) for x in X_test]
error = [np.abs(y_t - y_p) for y_t, y_p in zip(y_test, y_predict)]
display(error)
sum(error)/len(error)

[array([3.74811293e-13]),
 array([3.19744231e-14]),
 array([8.70414851e-13]),
 array([2.06057393e-13]),
 array([6.76791956e-13]),
 array([9.14823772e-14]),
 array([1.47615253e-12]),
 array([9.05941988e-13]),
 array([2.71782596e-13]),
 array([2.09610107e-13])]

array([5.11501952e-13])

So this is running much better now, it is fast, requires no iterations, however it will likley not be a good result if the
number of features or number of samples are to large.  

## Vectorize the Solution

At this point we have a naive, python solution that manually iterates through each value... and it is slow.
For this next step lets go ahead and `vectorize` the solution using numpy.  

To make things simplier, lets look at the algorithm again.  Gradient descent is defined below (for a single value of $\theta$).  

$$
  \theta_0 := \theta_0 - \alpha\frac{1}{m}\sum_{i=1}^{m}(h_\theta(x^{(i)}) - y^{(i)})* x_0^{(i)}    
$$

Looking at this, we want to vectorize the solution and I am going to break up the above into a few pieces that can be vectorized.

The first piece is $(h_\theta(x^{(i)}) - y^{(i)})$ which we will call $H$ so now our algorithm looks like this.  

$$
  \theta_0 := \theta_0 - \alpha\frac{1}{m}\sum_{i=1}^{m}H* x_0^{(i)}    
$$

The next thing is to realize that we are going to use all the values of of $x$ instead of just $x_0$ we will call this value $x$
Because we are removing the subscript for $x$ we are also goign to do so from $\theta$ so now our solution looks like this.  

$$
  \theta := \theta - \alpha\frac{1}{m}\sum_{i=1}^{m}H* x^{(i)}    
$$

The final piece is the summation and the division of $\frac{1}{m}$ so we can replace that entire section 
$\frac{1}{m}\sum_{i=1}^{m}H* x^{(i)}$ body with a single value of $R$ so our final equation looks like this.  

$$
  \theta := \theta - \alpha{R}
$$

So lets go ahead and vectorize our below solution.  

In [98]:
def gradient_descent(weights, X, y, learning_rate=0.001, convergence=0.001, loops=None):
    assert len(X) == len(y)
    assert len(weights) == len(X[0])+1  # The extra one is because we are treating x_0 as a 1 and the weight as the bias
    
    loops = loops or 10
    
    weight_len = len(weights)
    weights = weights.reshape((weight_len, 1))
    m = len(X)
    X = np.concatenate([np.ones((m,1)), np.array(X)], 1)
    y = np.array(y).reshape((m,1))
    
    for i in range(loops):
        H = (X @ weights) - y
        H = H * X
        R = np.sum(H, axis=0) / m
        weights = weights - (learning_rate * R.reshape((weight_len, 1)))
            
    return weights.reshape((weight_len,))

In [99]:
X_all = [list(np.random.rand(2)) for _ in range(110)]
y_all = [(3 + (2.5 * i[0]) + (4 * i[1]) + (1.8 * np.exp(i[0])) + (1.1 * i[0] * i[1])) for i in X_all]

X = [[i[0], i[1], np.exp(i[0]), np.exp(i[1]), i[0] * i[1]] for i in X_all[:-10]]
y = y_all[:-10]

X_test = [[i[0], i[1], np.exp(i[0]), np.exp(i[1]), i[0] * i[1]] for i in X_all[-10:]]
y_test = y_all[-10:]

weights = np.random.rand(6)
weights

array([0.59675837, 0.32754248, 0.13267929, 0.13936937, 0.2831722 ,
       0.76037036])

In [100]:
trained_weights = gradient_descent(weights, X, y, loops=10000)
trained_weights

array([1.31953814, 1.2395394 , 0.67826498, 2.31101111, 1.779575  ,
       1.2840817 ])

Now that we have the weights from a vectorized solution, lets see what our error looks like.  

In [101]:
y_predict = [(trained_weights[0] + sum([t * i for t, i in zip(trained_weights[1:], x)])) for x in X_test]
error = [np.abs(y_t - y_p) for y_t, y_p in zip(y_test, y_predict)]
display(error)
sum(error)/len(error)

[0.4662471887637345,
 0.06909434327168995,
 0.37320147154070327,
 0.13137964775737032,
 0.2013382151436831,
 0.14950287614054503,
 0.057902822268445675,
 0.12831205868814344,
 0.07050953313523678,
 0.13597349102606593]

0.1783461647735618